version: '3.8'

services:
  vrumapp.api:
    image: wrcelovrumappapi
    container_name: vrumapp.api
    build:
      context: .
      dockerfile: src/Wrcelo.VrumApp.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      vrumapp.database:
        condition: service_healthy
      vrumapp.rabbitmq:
        condition: service_healthy
      vrumapp.minio:
        condition: service_healthy
    restart: on-failure

  vrumapp.database:
    image: postgres:latest
    container_name: vrumapp.database
    environment:
      - POSTGRES_DB=vrumdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vrum123
    volumes:
      - ./containers/vrumdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  vrumapp.rabbitmq:
    image: rabbitmq:3-management
    container_name: vrumapp.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  vrumapp.minio:
    image: minio/minio
    container_name: vrumapp.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./containers/minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10